### PR TITLE
Fix file download, properly show if profile is private

### PR DESCRIPTION
**Pull request by nns33213**
Implement suggestion by @VasiliPupkin256 in https://github.com/arc298/instagram-scraper/pull/760#issuecomment-1018050569 in case IG does something weird.

--

`scrape` function warns the user if a profile he's trying to scrap is private. For unknown reason it does some extra checks rather than simply test the value of `is_private`. This produces wrong results in some cases:

- you can have a private profile that has zero posts - it doesn't matter since it may have stories that you can't access
- recently IG added a feature that a post can have multiple authors. In this case you can still scrape posts that are co-authored by the private profile if the other one is public

--

When scraping to a VirtualBox shared folder, I often experience a bug where the `download` function would throw `[Errno 2] No such file or directory` when trying to rename `.part` files. While I couldn't pinpoint the exact reason yet, I suspect that there is a race condition when the exact same item is being downloaded concurrently from multiple sources (e.g. highlights and stories). The files are not corrupted for some reason, but it fails to set the file creation date. This is fixed by doing the following:

1. If there's no `.part` file, proceed but warn the user
2. If we don't know the item timestamp, leave the file alone and don't force set `time.time()` (which is redundant anyway)
3. Remove the unnecessary conversion, since `__get_timestamp` already returns `int`

### CODE REVIEW

**Review by AlexNik — APPROVED** [review]

**Comment by VasiliPupkin256** [comment]
This error "no such file" or on the other hand access denied of the destination file is caused by simultaneous download of stories and highlights. New stories could already be in highlights. I think it could be solved by a set of filenames currently being downloaded, test it and exit download function on repeats.

**Comment by AlexNik** [comment]
@nns33213 Could you rebase you branch to Master and leave only the one commit please?

**Comment by AlexNik** [comment]
@nns33213 something goes wrong... (

**Comment by nns33213** [comment]
> @nns33213 something goes wrong... (

@AlexNik yeah, I know. I think you should be able to reopen the pull request, though. Or just merge the branch to avoid further spam, it's not terribly important.

**Review by AlexNik — APPROVED** [review]

**Pull request merged**
