### PR TITLE
Business info

### PR DESCRIPTION
**Pull request by ibrahim-mousa**
Add business name, phone number, category and external url to profile_info

### CODE REVIEW

**Comment by FatemeKhodayari** [comment]
@ibrahim-mousa I've received an email for this pr but don't know the reason. Should I do anything here? :)

**Comment by ibrahim-mousa** [comment]
idk why you received an email tbh, I just made a PR

**Comment by AlexNik** [comment]
@ibrahim-mousa is it correct for non business accounts?
Is any checking is needed?

**Comment by ibrahim-mousa** [comment]
@AlexNik All these fields return `None` if its not a business account.

**Review by AlexNik — APPROVED** [review]

**Comment by AlexNik** [comment]
@ibrahim-mousa thanks

**Pull request merged**
