### PR TITLE
My account was hacked I just want all my pics 

### PR DESCRIPTION
**Pull request by louloustar85**
Data if possible! 
its    lou_short_

### CODE REVIEW

**Comment by louloustar85** [comment]
#What kind of access do you guys need

**Comment by louloustar85** [comment]
So did this work? I'm kinda new and lost on what now.

**Comment by louloustar85** [comment]
Shit never mind I see the issue it won't work with private profiles! Right?

**Comment by AlexNik** [comment]
@louloustar85 nobody can't download any data from private profile if  he isn't the follower.
You could ask any your friend who follows your profile to download your data with this program.

**Pull request closed without merging**
