### PR TITLE
Fix GraphQL error properly, make the app work again

### PR DESCRIPTION
**Pull request by nns33213**
Recently, Instagram pushed an API update to many users that broke instagram-scraper with GraphQL errors. @novitae proposed a fix a while back in pull request https://github.com/arc298/instagram-scraper/pull/742 but it actually does not work and silently swallows video posts in the process.

I have tested on several accounts and the error is gone.

This fixes https://github.com/arc298/instagram-scraper/issues/739
Pull request https://github.com/arc298/instagram-scraper/pull/742 is obsolete.

### CODE REVIEW

**Comment by VasiliPupkin256** [comment]
Are you downloading all the image resolutions?

**Comment by nns33213** [comment]
> Are you downloading all the image resolutions?

@VasiliPupkin256 I have verified that the first item always contains the highest resolution image and the highest resolution video.

**Comment by VasiliPupkin256** [comment]
I can confirm that the best resolution video and photo is always going the first, for know. But in my version of fix I've added this function anyway, you can use it too

     def _best_candidate(self, candidates):
        best = 0
        for candidate in candidates:
            if candidate['height'] > best:
                url = candidate['url']
                best = candidate['height']
        if best > 0:
            return url
        for candidate in candidates:
            if candidate['width'] > best:
                url = candidate['url']
                best = candidate['width']
        if best > 0:
            return url
        return candidates[0]['url']

add I also removed this redundant `try .. except` proposed by @novitae moving the condition to the `elif` chain above.

**Comment by VasiliPupkin256** [comment]
In your case it will be something like

    elif 'display_url' in details:
        node['urls'] = [self.get_original_image(details['display_url'])]
    else:
        for ....

**Comment by VasiliPupkin256** [comment]
Sorry, but sorting by height is not enough, I've found posts where all videos had height 0 but different width and vice verse

**Comment by nns33213** [comment]
> Sorry, but sorting by height is not enough, I've found posts where all videos had height 0 but different width and vice verse

@VasiliPupkin256 were the videos really zero-height, though? I'm not sure if we should trust Instagram to give us the correct data (you've shown that it's faulty sometimes) or just pick the first candidate, which we know is the best version (at least for now).

**Comment by VasiliPupkin256** [comment]
> were the videos really zero-height, though

Yes, this post has all video versions reported to have zero height https://www.instagram.com/p/BlBezeeDcIN/

>  the best version (at least for now)

I more trust in reported dimensions still. If both height and width are zero then we may choose the first candidate. I didn't find counterexample though... but this could be just a coincidence and instagram had no specific intention to report higher resolution candidate first, may be they are ordered by time of processing or whatever. We may show warning if this order is violated then.

**Comment by VasiliPupkin256** [comment]
On the other hand this situation is so rare. Usually 1 or 2 posts per account. Even if we choose the wrong resolution there it wouldn't be a tragedy.

**Comment by kolbyg** [comment]
@nns33213 Just want to say thank you for getting this fixed up so quickly. I just pulled your repo with the changes and it's now scraping again. I can see in all cases of the couple accounts that I tested on, it did seem to pull the highest resolution files.
Hopefully this PR gets merged in quickly, as it seems to be completely broken without it now.

**Review by AlexNik — APPROVED** [review]

**Comment by novitae** [comment]
> Recently, Instagram pushed an API update to many users that broke instagram-scraper with GraphQL errors. @novitae proposed a fix a while back in pull request #742 but it actually does not work and silently swallows video posts in the process.
> 
> I have tested on several accounts and the error is gone.
> 
> This fixes #739 Pull request #742 is obsolete.

nice job !

**Pull request merged**
