### PR TITLE
disable downloading media, store json files only.

### PR DESCRIPTION
**Pull request by smb-h**
issued [here](https://github.com/arc298/instagram-scraper/issues/588)

### CODE REVIEW

**Comment by VasiliPupkin256** [comment]
Why do you think that everyone should just switch to the new `data` download directory instead of the current one?
Does renewal of the tor exit node actually help against 429 errors? When I've last checked 429 error was associated to the authenticated user and I weren't able to overcome it by simply connecting through different proxy.

**Comment by VasiliPupkin256** [comment]
This is a public repository, stop pushing your local developing commits here

**Comment by smb-h** [comment]
Ops! sry about that i will close this one.
the `data` dir will help to manage scraped data, and better structure of course. about tor, Yes! it did help me to overcome 429 and it works perfectly but the thing is to renew an ip it takes a bit of time so it works a bit slower but no more 429. if its fine tell me to close this and send a pull request with tor proxy edit.


> This is a public repository, stop pushing your local developing commits here

**Comment by VasiliPupkin256** [comment]
I've tested it. I've deliberately put one of my scrape account into 429 limbo and it doesn't work if I connect through Tor either. But it may help you or someone else... I don't know, instagram blocking heuristic is weird. An option to set Tor proxy and command it to rebuild circuits on demand could be interesting if implemented carefully.

**Comment by smb-h** [comment]
> I've tested it. I've deliberately put one of my scrape account into 429 limbo and it doesn't work if I connect through Tor either. But it may help you or someone else... I don't know, instagram blocking heuristic is weird. An option to set Tor proxy and command it to rebuild circuits on demand could be interesting if implemented carefully.

After 2 days running the script on server, logged account finally got banned. I did add a few things to log more detail, it did scrap 100 posts per hour, it was good i think but unfortunately after encountering an error depends on try for ever or not it didn't save data until it ends successfully, tho to speed i mentioned i think we can save data during process, so i decided to work on this matter too. About tor i think it helps to scrap some more data than usual. I have worked with various tools and stuff to crawl this platform but think this projects has potential to do this job perfectly. i would be more happy to help on these matters

**Pull request closed without merging**
